# Generated by Django 3.0.4 on 2020-04-25 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emple_id', models.IntegerField(max_length=9)),
                ('first_name', models.CharField(max_length=50)),
                ('midle_i', models.CharField(max_length=1)),
                ('last_name', models.CharField(max_length=30)),
                ('emails', models.EmailField(max_length=254)),
                ('fun_fac', models.TextField(blank=True)),
            ],
        ),
    ]
