# Generated by Django 3.0.4 on 2020-04-25 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Porfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='emple_id',
            field=models.IntegerField(),
        ),
    ]
