# Generated by Django 3.0.4 on 2020-04-28 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Porfolio', '0002_auto_20200425_0605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='emails',
        ),
    ]
