# Generated by Django 3.0.4 on 2020-04-28 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Porfolio', '0003_remove_member_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='emails',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
