# Generated by Django 3.0.4 on 2020-04-28 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Porfolio', '0004_member_emails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='emails',
            field=models.CharField(default=True, max_length=50),
        ),
    ]
