# Generated by Django 3.0.4 on 2020-04-29 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Porfolio', '0005_auto_20200428_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='emails',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
